name: Extract JSON Details

on:
  push:
    branches:
      - main

jobs:
  extractDetails:
    runs-on: ubuntu-latest

    steps:
      - name: Access JSON data
        id: access
        run: |
          #echo '{"count":124,"contentResources":[{"id":"IflowForDevOpsTest","resourceID":"f3b1dc1cd5c34ce9a8a8b027d0edc418","type":"CloudIntegration","name":"Iflow For DevOps Test","subType":"package","version":"","title":"Test Iflow created by DevOps team for pipeline","vendor":"","description":"<p></p>","contentUrl":null,"componentQueryPattern":null,"components":[{"id":"Trial_Integration_Flow","name":"Trial Integration Flow","type":"Integration Flow","version":"1.0.1","additionalProperties":null,"exportable":false}],"dependencies":[],"additionalProperties":{"ExportMode":"ZIP"}},{"id":"IPOSTTest","resourceID":"0217163f50b643d3adaeef5d891cee96","type":"CloudIntegration","name":"IPOST Test","subType":"package","version":"","title":"IPOSTTest","vendor":"","description":"<p></p>","contentUrl":null,"componentQueryPattern":null,"components":[{"id":"IPost_iFlow","name":"IPost iFlow","type":"Integration Flow","version":"Active","additionalProperties":null,"exportable":false}],"dependencies":[],"additionalProperties":{"ExportMode":"ZIP"}}]}' >> json_data.json
          curl --write-out "%{http_code}" -X PUT 'https://cpg-gpc-xt-hub.atlassian.net/rest/api/2/issue/${{env.ricefw_id}}' -H 'Accept: application/json' -H 'Content-Type: application/json' -d @/home/runner/work/test2/test2/json/payload.json --user "...:ATATT3xFfGF0B7XLKDLU9Tpt8ah0uTTXoW-fGERs6Ql27I8AViKJ0G5N6utBLFx-TI0Z4bLJiL0t2dCfsGMeKyzd616sDQgQidsHE6jceTr_xU_IsH6NqHU4yWn_i16dCU94vrw4qlxoON_4ddbKC-UqFLH6FghM9hG9NxAmMO0gIhXyfhpdSUA=AA53A3AA"
      - name: Extract Details
        id: extract
        run: |
         json_data=$(cat json_data.json)

          component_id=$(echo "$json_data" | jq -r '.contentResources[].components[] | select(.name == "IPost iFlow") | .id')
          echo "test=$component_id" >> "$GITHUB_OUTPUT"

      - name: extracted component id
        run: |
          extracted_component_id="${{ steps.extract.outputs.test }}"
          echo "Extracted Component ID: $extracted_component_id"
